# encoding: utf-8
#
# Redmine plugin to execute untrusted code
#
# Copyright © 2021 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

##########################################################################################
# variables for production environment
##########################################################################################
#production:
##########################################################################################
# create: docker variables to create a docker
##########################################################################################
# create:
##########################################################################################
# Hostname: default nil
##########################################################################################
#    Hostname:                ''
##########################################################################################
# Domainname: default nil
##########################################################################################
#    Domainname:              ''
##########################################################################################
# User: default nil
##########################################################################################
#    User:                    ''
##########################################################################################
# CpuShares: default 1
##########################################################################################
#   CpuShares:                1,
##########################################################################################
# Memory: default 50 Mb
##########################################################################################
#   Memory:                   52_428_800
##########################################################################################
# MemorySwap: default nil
##########################################################################################
#    MemorySwap:              52_428_800
##########################################################################################
# Env: default nil
##########################################################################################
#    Env:                     ['USE_QUOTAS=1']
##########################################################################################
# Cpuset: default nil
##########################################################################################
#    Cpuset:                  '0,1'
##########################################################################################
# AttachStdin: default false, should not be changed
##########################################################################################
#   AttachStdin:              false
##########################################################################################
# AttachStderr: default true, should not be changed
##########################################################################################
#   AttachStderr:             true
##########################################################################################
# AttachStdout: default true, should not be changed
##########################################################################################
#   AttachStdout:             true
##########################################################################################
# PortSpecs: default nil
##########################################################################################
#    PortSpecs:               null
##########################################################################################
# Tty: default true, should not be changed: if set to false 8 Bytes are prepended to logs
##########################################################################################
#   Tty:                      true
##########################################################################################
# OpenStdin: default false, should not be changed
##########################################################################################
#   OpenStdin:                false
##########################################################################################
# StdinOnce: default false, should not be changed
##########################################################################################
#   StdinOnce:                false
##########################################################################################
# Cmd: default [], should not be changed
##########################################################################################
#   Cmd:                      []
##########################################################################################
# Image: default redmine_scripting_engine:latest
##########################################################################################
#   Image:                    redmine_scripting_engine:latest
##########################################################################################
# Volumes: default {'/home/sandbox/src' => {}}
##########################################################################################
#   Volumes:
#     /home/sandbox/src:      {}
##########################################################################################
# WorkingDir: default nil
##########################################################################################
#    WorkingDir:              ''
##########################################################################################
# NetworkDisabled: default true
##########################################################################################
#   NetworkDisabled:          true
##########################################################################################
# ExposedPorts: default {'22/tcp' => {}}
##########################################################################################
#    ExposedPorts:                                                      
#      22/tcp:                {}                                        

##########################################################################################
# development: variables for development environment
##########################################################################################
# development:

##########################################################################################
# cert: variables for certificate files
##########################################################################################
# cert:
#   private_key_path:        code_cert/key.pem
#   certificate_path:        code_cert/cert.pem
#   ssl_verify_peer:         false

##########################################################################################
# start: variables for starting docker container
##########################################################################################
# start:
##########################################################################################
# Binds: default: ["tmp/code_dirs:/home/sandbox/src"]
##########################################################################################
#   Binds:                    ["tmp/code_dirs:/home/sandbox/src"]        # backed
##########################################################################################
# Links: default: nil
##########################################################################################
#    Links:                   ['redis3:redis']                           
##########################################################################################
# LxcConf: default: nil
##########################################################################################
#    LxcConf:                                                            
#      lxc.utsname:           'docker'                                   
##########################################################################################
# PortBindings: default: nil
##########################################################################################
#    PortBindings:                                                       
#      22/tcp:                [{'HostPort' => '11022'}]                  
##########################################################################################
# PublishAllPorts: default: nil
##########################################################################################
#    PublishAllPorts:         false                                      
##########################################################################################
# Privileged: default: nil
##########################################################################################
#    Privileged:              false                                      
##########################################################################################
# Dns: default: nil
##########################################################################################
#    Dns:                     ['8.8.8.8']                                
##########################################################################################
# VolumesFrom: default: nil
##########################################################################################
#    VolumesFrom:             ['parent', 'other:ro']                     
##########################################################################################
# CapAdd: default: nil
##########################################################################################
#    CapAdd:                  ['NET_ADMIN']                              
##########################################################################################
# CapDrop: default: nil
##########################################################################################
#    CapDrop:                 ['MKNOD']                                  

##########################################################################################
# rse: variables for Redmine Scripting Engine
##########################################################################################
#  rse:
##########################################################################################
# dockersourcedir: default: '/home/sandbox/src', absolute path in docker container
##########################################################################################
#   dockersourcedir:          /home/sandbox/src
##########################################################################################
# dockerattsdir: default: /home/sandbox/src, absolute path in docker container
##########################################################################################
#   dockerattsdir:          /home/sandbox/atts
##########################################################################################
# servermountdirs: default: File.join(Rails.root, "tmp", "docker_dirs")
##########################################################################################
#    servermountdirs:          <provide absolute path to dir>
##########################################################################################
# timeout: default: 15
##########################################################################################
#   timeout:                  15
##########################################################################################
# keepcontainer: default: false
##########################################################################################
#   keepcontainer:            false
##########################################################################################
# keepmountdir: default: false
##########################################################################################
#    keepmountdir:             true
##########################################################################################
# unprotectedmode: default: false, if true, run in redmine's rails environment
##########################################################################################
#   unprotectedmode:          false
  