source 'https://rubygems.org'

gem 'activesupport'
gem 'actionview'
gem 'open3'
gem 'rubyzip'
gem 'rmagick'
gem 'faker'
gem 'rqrcode'
gem 'mimemagic'

# HugoHasenbein gems

gem 'deep_try'
gem 'hash_base'
gem 'redmine_api_helper'

